# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 4d.be
email: joachim@4d.be
description: focused on making things simple.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://4d.be" # the base hostname & protocol for your site
twitter_username: JoachimVdH
github_username: joachimVdH

# Build settings
markdown: kramdown
destination: public
exclude: ["Rakefile", "README.md", "public", "jekyll", "Gemfile", "Guardfile","node_modules"]

gems:
  - jekyll-sitemap
